"""Offline Xiaoheihe emoji identifiers and conservative input aliases.

The live account emoji endpoint remains the source of truth.  This snapshot
keeps replies usable when that endpoint is unavailable and documents the
identifiers observed in the web client and public emoji assets on 2026-08-11.
"""

from __future__ import annotations

from typing import Final

XHH_EMOJI_STANDARD_SNAPSHOT_NAMES: Final[frozenset[str]] = frozenset(
    {
        "bigemoji_？",
        "bigemoji_暗中观察",
        "bigemoji_比心",
        "bigemoji_吃瓜",
        "bigemoji_打折",
        "bigemoji_风纪委员",
        "bigemoji_哈哈",
        "bigemoji_滑稽",
        "bigemoji_开可乐",
        "bigemoji_厉害",
        "bigemoji_求带",
        "bigemoji_摔",
        "bigemoji_委屈",
        "bigemoji_喜加一",
        "bigemoji_羡慕",
        "bigemoji_做梦",
        "cube_+1",
        "cube_-1",
        "cube_2023",
        "cube_2024",
        "cube_2025",
        "cube_2026",
        "cube_doge",
        "cube_H币",
        "cube_P的谎言",
        "cube_wota",
        "cube_爱心",
        "cube_比心",
        "cube_比耶",
        "cube_闭嘴",
        "cube_并不简单",
        "cube_菜doge",
        "cube_沧桑",
        "cube_超人",
        "cube_炒菜",
        "cube_吃瓜",
        "cube_吃鸡啦",
        "cube_吹口哨",
        "cube_打脸",
        "cube_打咩",
        "cube_蛋糕",
        "cube_点赞",
        "cube_电牛",
        "cube_鹅",
        "cube_感动",
        "cube_咕咕",
        "cube_鼓掌",
        "cube_乖",
        "cube_害羞",
        "cube_汗",
        "cube_盒十",
        "cube_黑人问号",
        "cube_红包",
        "cube_滑稽",
        "cube_毁灭战士",
        "cube_鸡毙你",
        "cube_加油",
        "cube_剑星渡鸦",
        "cube_剑星伊芙",
        "cube_僵尸",
        "cube_惊讶",
        "cube_开心",
        "cube_哭泣",
        "cube_酷",
        "cube_困",
        "cube_来财",
        "cube_浪人砍一刀",
        "cube_良民",
        "cube_灵光一闪",
        "cube_洛的点赞",
        "cube_马年吉祥",
        "cube_玫瑰",
        "cube_猛男微笑",
        "cube_摸摸头",
        "cube_你懂我",
        "cube_怒",
        "cube_柠檬",
        "cube_欧润吉",
        "cube_喷水",
        "cube_碰拳",
        "cube_凄凉",
        "cube_庆祝",
        "cube_庆祝-圣诞",
        "cube_山姆无奈",
        "cube_上学-乐",
        "cube_上学-丧",
        "cube_生气",
        "cube_圣诞树",
        "cube_时间旅者",
        "cube_睡觉",
        "cube_太酷啦",
        "cube_摊手",
        "cube_叹气",
        "cube_吐",
        "cube_哇",
        "cube_微笑",
        "cube_委屈",
        "cube_窝囊",
        "cube_我懂你",
        "cube_我方了",
        "cube_握草",
        "cube_捂脸哭",
        "cube_悟空",
        "cube_嬉水女王",
        "cube_喜+1",
        "cube_喜欢",
        "cube_吓",
        "cube_小鸡",
        "cube_笑cry",
        "cube_学习",
        "cube_阳",
        "cube_耶",
        "cube_晕",
        "cube_赞",
        "cube_摘墨镜",
        "cube_这是什么鸟",
        "grandemoji_awsl",
        "grandemoji_mur化",
        "grandemoji_痴",
        "grandemoji_盒弹来袭",
        "grandemoji_交个朋友",
        "grandemoji_摸不着头脑",
        "grandemoji_爬",
        "grandemoji_爬了",
        "grandemoji_啥玩意",
        "grandemoji_缩",
        "grandemoji_躺平",
        "grandemoji_万能盒娘",
        "grandemoji_我很可爱",
        "grandemoji_呀嘞呀嘞",
        "grandemoji_整挺好",
        "grandemoji_做个好梦",
        "heygirl_rua!",
        "heygirl_挨刀",
        "heygirl_白嫖怪",
        "heygirl_吃瓜",
        "heygirl_痴",
        "heygirl_诶嘿",
        "heygirl_哈哈",
        "heygirl_害羞",
        "heygirl_喝奶茶",
        "heygirl_滑稽",
        "heygirl_记下来",
        "heygirl_惊",
        "heygirl_开可乐",
        "heygirl_哭",
        "heygirl_苦酒入喉",
        "heygirl_捏脸",
        "heygirl_敲开心",
        "heygirl_茄化",
        "heygirl_偷看",
        "heygirl_秃",
        "heygirl_无语",
        "heygirl_喜欢",
        "heygirl_疑问",
        "heygirl_这…",
    }
)

# Older web/client metadata used these spellings for the same assets. Keep
# them as input-compatible fallbacks, but do not present them as standard IDs.
XHH_EMOJI_FALLBACK_NAMES: Final[frozenset[str]] = (
    XHH_EMOJI_STANDARD_SNAPSHOT_NAMES
    | frozenset({"cube_剑星涂鸦", "heygirl_耶嘿"})
)


# Each group starts with one or more real identifiers.  Remaining entries
# are common Chinese/English forms that models may produce for the same art.
XHH_EMOJI_ALIAS_GROUPS: Final[tuple[tuple[str, ...], ...]] = (
    ("cube_doge", "cube_狗头", "cube_doghead", "cube_dog", "cube_shiba"),
    ("cube_吐", "cube_吐血", "cube_vomit", "cube_puke"),
    (
        "cube_剑星渡鸦",
        "cube_剑星涂鸦",
        "cube_stellarblade_raven",
        "cube_stellar_blade_raven",
        "cube_stellar_blade_graffiti",
    ),
    ("heygirl_诶嘿", "heygirl_耶嘿", "heygirl_ehehe", "heygirl_yehey"),
    ("cube_+1", "cube_plus1", "cube_plus_one"),
    ("cube_-1", "cube_minus1", "cube_minus_one"),
    ("cube_2023", "cube_year_2023", "cube_2023year"),
    ("cube_2024", "cube_year_2024", "cube_2024year"),
    ("cube_2025", "cube_year_2025", "cube_2025year"),
    ("cube_2026", "cube_year_2026", "cube_2026year"),
    ("cube_H币", "cube_hcoin", "cube_h_coin"),
    ("cube_P的谎言", "cube_lies_of_p", "cube_liesofp"),
    ("cube_wota", "cube_glowstick", "cube_cheerstick"),
    ("cube_爱心", "cube_heart", "cube_love_heart"),
    ("cube_比心", "cube_finger_heart", "cube_fingerheart"),
    ("cube_比耶", "cube_peace", "cube_victory"),
    ("cube_闭嘴", "cube_shut_up", "cube_zipper_mouth"),
    ("cube_并不简单", "cube_not_simple", "cube_complicated"),
    ("cube_菜doge", "cube_noob_doge", "cube_bad_doge"),
    ("cube_沧桑", "cube_weathered", "cube_world_weary"),
    ("cube_超人", "cube_superman"),
    ("cube_炒菜", "cube_cooking", "cube_stir_fry"),
    ("cube_吃瓜", "cube_gossip", "cube_melon"),
    ("cube_吃鸡啦", "cube_pubg_win", "cube_chicken_dinner"),
    ("cube_吹口哨", "cube_whistle"),
    ("cube_打脸", "cube_slap", "cube_face_slap"),
    ("cube_打咩", "cube_dame", "cube_no"),
    ("cube_蛋糕", "cube_cake"),
    ("cube_点赞", "cube_thumbs_up", "cube_thumbsup"),
    ("cube_电牛", "cube_electric_bull"),
    ("cube_鹅", "cube_goose"),
    ("cube_感动", "cube_touched", "cube_moved"),
    ("cube_咕咕", "cube_gugu", "cube_coo"),
    ("cube_鼓掌", "cube_clap", "cube_applause"),
    ("cube_乖", "cube_good", "cube_well_behaved"),
    ("cube_害羞", "cube_shy", "cube_embarrassed"),
    ("cube_汗", "cube_sweat"),
    ("cube_盒十", "cube_box_ten", "cube_heybox_ten"),
    ("cube_黑人问号", "cube_black_question", "cube_confused"),
    ("cube_红包", "cube_red_packet", "cube_red_envelope"),
    ("cube_滑稽", "cube_funny", "cube_silly"),
    ("cube_毁灭战士", "cube_doom", "cube_doom_slayer"),
    ("cube_鸡毙你", "cube_chicken_kill"),
    ("cube_加油", "cube_cheer", "cube_keep_going"),
    ("cube_剑星伊芙", "cube_stellarblade_eve", "cube_stellar_blade_eve"),
    ("cube_僵尸", "cube_zombie"),
    ("cube_惊讶", "cube_surprised", "cube_amazed"),
    ("cube_开心", "cube_happy", "cube_joy"),
    ("cube_哭泣", "cube_cry", "cube_crying"),
    ("cube_酷", "cube_cool"),
    ("cube_困", "cube_sleepy", "cube_tired"),
    ("cube_来财", "cube_get_rich", "cube_money"),
    ("cube_浪人砍一刀", "cube_ronin", "cube_samurai_slash"),
    ("cube_良民", "cube_good_citizen"),
    ("cube_灵光一闪", "cube_idea", "cube_lightbulb"),
    ("cube_洛的点赞", "cube_luo_like", "cube_luo_thumbs_up"),
    ("cube_马年吉祥", "cube_horse_year", "cube_happy_horse_year"),
    ("cube_玫瑰", "cube_rose"),
    ("cube_猛男微笑", "cube_macho_smile"),
    ("cube_摸摸头", "cube_head_pat", "cube_pat_head"),
    ("cube_你懂我", "cube_you_know_me"),
    ("cube_柠檬", "cube_lemon"),
    ("cube_怒", "cube_rage", "cube_furious"),
    ("cube_欧润吉", "cube_orange"),
    ("cube_喷水", "cube_spray", "cube_spit"),
    ("cube_碰拳", "cube_fist_bump", "cube_fistbump"),
    ("cube_凄凉", "cube_desolate", "cube_miserable"),
    ("cube_庆祝", "cube_celebrate", "cube_celebration"),
    ("cube_庆祝-圣诞", "cube_christmas_celebrate"),
    ("cube_山姆无奈", "cube_sam_helpless"),
    ("cube_上学-乐", "cube_school_happy"),
    ("cube_上学-丧", "cube_school_sad"),
    ("cube_生气", "cube_angry", "cube_mad"),
    ("cube_圣诞树", "cube_christmas_tree"),
    ("cube_时间旅者", "cube_time_traveler", "cube_time_traveller"),
    ("cube_睡觉", "cube_sleep"),
    ("cube_太酷啦", "cube_awesome", "cube_so_cool"),
    ("cube_摊手", "cube_shrug"),
    ("cube_叹气", "cube_sigh"),
    ("cube_哇", "cube_wow"),
    ("cube_微笑", "cube_smile"),
    ("cube_委屈", "cube_aggrieved", "cube_wronged"),
    ("cube_窝囊", "cube_pathetic"),
    ("cube_我懂你", "cube_i_know_you"),
    ("cube_我方了", "cube_panicked", "cube_panic"),
    ("cube_握草", "cube_shocked", "cube_holy_shit"),
    ("cube_捂脸哭", "cube_crying_facepalm"),
    ("cube_悟空", "cube_wukong"),
    ("cube_嬉水女王", "cube_water_queen"),
    ("cube_喜+1", "cube_plus_like", "cube_like_plus_one"),
    ("cube_喜欢", "cube_like", "cube_love"),
    ("cube_吓", "cube_scared", "cube_frightened"),
    ("cube_小鸡", "cube_chick"),
    ("cube_笑cry", "cube_laugh_cry", "cube_laughing_crying"),
    ("cube_学习", "cube_study", "cube_learning"),
    ("cube_阳", "cube_positive", "cube_covid_positive"),
    ("cube_耶", "cube_yay"),
    ("cube_晕", "cube_dizzy"),
    ("cube_赞", "cube_praise", "cube_approve"),
    ("cube_摘墨镜", "cube_remove_sunglasses"),
    ("cube_这是什么鸟", "cube_what_bird"),
    ("bigemoji_？", "bigemoji_question", "bigemoji_question_mark"),
    ("bigemoji_暗中观察", "bigemoji_peek", "bigemoji_observe"),
    ("bigemoji_比心", "bigemoji_finger_heart"),
    ("bigemoji_吃瓜", "bigemoji_gossip", "bigemoji_melon"),
    ("bigemoji_打折", "bigemoji_discount"),
    ("bigemoji_风纪委员", "bigemoji_discipline_monitor"),
    ("bigemoji_哈哈", "bigemoji_haha", "bigemoji_lol"),
    ("bigemoji_滑稽", "bigemoji_funny"),
    ("bigemoji_开可乐", "bigemoji_open_cola"),
    ("bigemoji_厉害", "bigemoji_impressive", "bigemoji_awesome"),
    ("bigemoji_求带", "bigemoji_carry_me"),
    ("bigemoji_摔", "bigemoji_fall", "bigemoji_trip"),
    ("bigemoji_委屈", "bigemoji_aggrieved"),
    ("bigemoji_喜加一", "bigemoji_plus_one_game"),
    ("bigemoji_羡慕", "bigemoji_envious"),
    ("bigemoji_做梦", "bigemoji_dream"),
    ("grandemoji_awsl", "grandemoji_awesome_life"),
    ("grandemoji_mur化", "grandemoji_murhua"),
    ("grandemoji_痴", "grandemoji_infatuated"),
    ("grandemoji_盒弹来袭", "grandemoji_box_attack"),
    ("grandemoji_交个朋友", "grandemoji_make_friend"),
    ("grandemoji_摸不着头脑", "grandemoji_confused"),
    ("grandemoji_爬", "grandemoji_crawl"),
    ("grandemoji_爬了", "grandemoji_left", "grandemoji_escaped"),
    ("grandemoji_啥玩意", "grandemoji_what"),
    ("grandemoji_缩", "grandemoji_shrink", "grandemoji_hide"),
    ("grandemoji_躺平", "grandemoji_lie_flat"),
    ("grandemoji_万能盒娘", "grandemoji_all_powerful_heybox_girl"),
    ("grandemoji_我很可爱", "grandemoji_i_am_cute"),
    ("grandemoji_呀嘞呀嘞", "grandemoji_oh_dear"),
    ("grandemoji_整挺好", "grandemoji_nice"),
    ("grandemoji_做个好梦", "grandemoji_sweet_dream"),
    ("heygirl_rua!", "heygirl_rua", "heygirl_rub"),
    ("heygirl_挨刀", "heygirl_stabbed", "heygirl_hit"),
    ("heygirl_白嫖怪", "heygirl_freeloader", "heygirl_free_loader"),
    ("heygirl_吃瓜", "heygirl_gossip", "heygirl_melon"),
    ("heygirl_痴", "heygirl_infatuated", "heygirl_love_struck"),
    ("heygirl_哈哈", "heygirl_haha", "heygirl_lol"),
    ("heygirl_害羞", "heygirl_shy", "heygirl_embarrassed"),
    ("heygirl_喝奶茶", "heygirl_milk_tea", "heygirl_bubble_tea"),
    ("heygirl_滑稽", "heygirl_funny", "heygirl_silly"),
    ("heygirl_记下来", "heygirl_note", "heygirl_write_down"),
    ("heygirl_惊", "heygirl_surprised", "heygirl_shocked"),
    ("heygirl_开可乐", "heygirl_open_cola"),
    ("heygirl_哭", "heygirl_cry", "heygirl_crying"),
    ("heygirl_苦酒入喉", "heygirl_bitter_wine", "heygirl_drink"),
    ("heygirl_捏脸", "heygirl_pinch_cheek", "heygirl_cheek_pinch"),
    ("heygirl_敲开心", "heygirl_so_happy", "heygirl_very_happy"),
    ("heygirl_茄化", "heygirl_eggplant", "heygirl_eggplantified"),
    ("heygirl_偷看", "heygirl_peek", "heygirl_sneak_peek"),
    ("heygirl_秃", "heygirl_bald"),
    ("heygirl_无语", "heygirl_speechless"),
    ("heygirl_喜欢", "heygirl_like", "heygirl_love"),
    ("heygirl_疑问", "heygirl_question", "heygirl_confused"),
    ("heygirl_这…", "heygirl_this", "heygirl_ellipsis"),
)
